-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.kiln_firing_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  kiln_id uuid,
  name text NOT NULL,
  description text,
  base_type text CHECK (base_type = ANY (ARRAY['bisque'::text, 'glaze'::text, 'raku'::text, 'pit'::text, 'saggar'::text, 'crystalline'::text, 'other'::text])),
  atmosphere text CHECK (atmosphere = ANY (ARRAY['oxidation'::text, 'reduction'::text, 'neutral'::text])),
  temperature_curve jsonb NOT NULL,
  estimated_duration integer,
  clay_compatibility ARRAY,
  glaze_compatibility ARRAY,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_firing_templates_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_firing_templates_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT kiln_firing_templates_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_firing_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_firings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  kiln_id uuid NOT NULL,
  template_id uuid,
  name text,
  scheduled_start timestamp with time zone,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  atmosphere text,
  target_cone text,
  notes text,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'loading'::text, 'firing'::text, 'cooling'::text, 'completed'::text, 'cancelled'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_firings_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_firings_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT kiln_firings_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_firings_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.kiln_firing_templates(id),
  CONSTRAINT kiln_firings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kilns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  location_id uuid,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['electric'::text, 'gas'::text, 'wood'::text, 'raku'::text])),
  manufacturer text,
  model text,
  serial_number text,
  capacity numeric,
  max_temp numeric,
  shelf_count integer,
  specs jsonb,
  status text DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'loading'::text, 'firing'::text, 'cooling'::text, 'maintenance'::text, 'out-of-service'::text])),
  install_date date,
  warranty_expiry date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kilns_pkey PRIMARY KEY (id),
  CONSTRAINT kilns_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT kilns_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text,
  handle text UNIQUE,
  email text UNIQUE,
  type text DEFAULT 'artist'::text CHECK (type = ANY (ARRAY['artist'::text, 'studio'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  phone text,
  artist_plan USER-DEFINED NOT NULL DEFAULT 'artist-free'::artist_plan,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.studio_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text, 'instructor'::text, 'member'::text, 'employee'::text])),
  token text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'revoked'::text, 'expired'::text])),
  invited_by uuid NOT NULL,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_by uuid,
  accepted_at timestamp with time zone,
  location_id uuid,
  membership_type text CHECK (membership_type::studio_membership_plan IS NOT NULL),
  name text,
  CONSTRAINT studio_invites_pkey PRIMARY KEY (id),
  CONSTRAINT studio_invites_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT studio_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id),
  CONSTRAINT studio_invites_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES public.profiles(id),
  CONSTRAINT studio_invites_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id)
);
CREATE TABLE public.studio_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  city text,
  state text,
  zip_code text,
  phone text,
  email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT studio_locations_pkey PRIMARY KEY (id),
  CONSTRAINT studio_locations_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id)
);
CREATE TABLE public.studio_membership_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::studio_membership_application_status,
  location_id uuid,
  requested_membership_type text,
  experience text,
  interests ARRAY,
  goals text,
  referral_source text,
  emergency_contact jsonb,
  custom_fields jsonb,
  submitted_at timestamp with time zone DEFAULT now(),
  decided_at timestamp with time zone,
  decided_by uuid,
  decision_reason text,
  CONSTRAINT studio_membership_applications_pkey PRIMARY KEY (id),
  CONSTRAINT studio_membership_applications_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT studio_membership_applications_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT studio_membership_applications_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id),
  CONSTRAINT studio_membership_applications_requested_membership_type_fkey FOREIGN KEY (requested_membership_type) REFERENCES public.studio_membership_plans(plan_code),
  CONSTRAINT studio_membership_applications_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.studio_membership_plans (
  plan_code text NOT NULL CHECK (plan_code::studio_membership_plan IS NOT NULL),
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  price_cents real CHECK (price_cents > 0.0::double precision),
  billing_interval text,
  CONSTRAINT studio_membership_plans_pkey PRIMARY KEY (plan_code)
);
CREATE TABLE public.studio_memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'member'::studio_role,
  created_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'active'::studio_membership_status,
  location_id uuid NOT NULL,
  membership_type text CHECK (membership_type::studio_membership_plan IS NOT NULL),
  CONSTRAINT studio_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT studio_memberships_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT studio_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT studio_memberships_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id)
);
CREATE TABLE public.studios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  handle text NOT NULL UNIQUE,
  email text NOT NULL,
  description text,
  plan text DEFAULT 'studio-solo'::text CHECK (plan = ANY (ARRAY['studio-solo'::text, 'studio-duo'::text, 'studio-pro'::text, 'studio-unlimited'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  max_members integer,
  max_locations integer,
  website text,
  CONSTRAINT studios_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_type text NOT NULL CHECK (owner_type = ANY (ARRAY['profile'::text, 'studio'::text])),
  owner_id uuid NOT NULL,
  plan_code text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  external_customer_id text,
  external_subscription_id text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);