-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.custom_firing_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  base_type text CHECK (base_type = ANY (ARRAY['bisque'::text, 'glaze'::text, 'raku'::text, 'pit'::text, 'saggar'::text, 'crystalline'::text, 'other'::text])),
  temperature_curve jsonb NOT NULL,
  atmosphere text CHECK (atmosphere = ANY (ARRAY['oxidation'::text, 'reduction'::text, 'neutral'::text])),
  estimated_duration integer,
  special_instructions text,
  clay_compatibility ARRAY,
  glaze_compatibility ARRAY,
  safety_notes text,
  is_default boolean DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_used timestamp with time zone,
  usage_count integer DEFAULT 0,
  CONSTRAINT custom_firing_types_pkey PRIMARY KEY (id),
  CONSTRAINT custom_firing_types_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT custom_firing_types_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_assignment_cover_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  reason text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'denied'::text])),
  covered_by uuid,
  covered_at timestamp with time zone,
  CONSTRAINT kiln_assignment_cover_requests_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_assignment_cover_requests_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.kiln_assignments(id),
  CONSTRAINT kiln_assignment_cover_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT kiln_assignment_cover_requests_covered_by_fkey FOREIGN KEY (covered_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_assignment_notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['assignment'::text, 'reminder'::text, 'start-alert'::text, 'completion-reminder'::text])),
  sent_at timestamp with time zone DEFAULT now(),
  acknowledged boolean DEFAULT false,
  CONSTRAINT kiln_assignment_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_assignment_notifications_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.kiln_assignments(id)
);
CREATE TABLE public.kiln_assignment_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  assignment_id uuid NOT NULL,
  description text NOT NULL,
  is_completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_assignment_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_assignment_tasks_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.kiln_assignments(id)
);
CREATE TABLE public.kiln_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kiln_id uuid NOT NULL,
  firing_id uuid NOT NULL,
  assigned_employee_id uuid NOT NULL,
  assigned_employee_name text NOT NULL,
  assignment_type text NOT NULL CHECK (assignment_type = ANY (ARRAY['loading'::text, 'monitoring'::text, 'unloading'::text, 'full-cycle'::text])),
  scheduled_start timestamp with time zone NOT NULL,
  scheduled_end timestamp with time zone NOT NULL,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  status text DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'in-progress'::text, 'completed'::text, 'cancelled'::text, 'needs-cover'::text])),
  special_instructions text,
  emergency_contact text,
  assigned_by uuid NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_assignments_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_assignments_firing_id_fkey FOREIGN KEY (firing_id) REFERENCES public.kiln_firings(id),
  CONSTRAINT kiln_assignments_assigned_employee_id_fkey FOREIGN KEY (assigned_employee_id) REFERENCES public.profiles(id),
  CONSTRAINT kiln_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_camera_recordings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  camera_id uuid NOT NULL,
  firing_id uuid NOT NULL,
  recording_type text NOT NULL CHECK (recording_type = ANY (ARRAY['live-stream'::text, 'time-lapse'::text, 'temperature-alert'::text, 'motion-detection'::text])),
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone,
  file_url text,
  thumbnail_url text,
  duration integer,
  file_size bigint,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_camera_recordings_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_camera_recordings_camera_id_fkey FOREIGN KEY (camera_id) REFERENCES public.kiln_cameras(id),
  CONSTRAINT kiln_camera_recordings_firing_id_fkey FOREIGN KEY (firing_id) REFERENCES public.kiln_firings(id)
);
CREATE TABLE public.kiln_cameras (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kiln_id uuid NOT NULL,
  camera_id text NOT NULL,
  position text NOT NULL CHECK ("position" = ANY (ARRAY['interior'::text, 'exterior'::text, 'control-panel'::text, 'pyrometer'::text])),
  is_active boolean DEFAULT true,
  monitoring_settings jsonb DEFAULT '{}'::jsonb,
  last_health_check timestamp with time zone,
  health_status text DEFAULT 'online'::text CHECK (health_status = ANY (ARRAY['online'::text, 'offline'::text, 'error'::text, 'maintenance'::text])),
  battery_level integer,
  signal_strength integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_cameras_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_cameras_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id)
);
CREATE TABLE public.kiln_firing_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  kiln_id uuid,
  name text NOT NULL,
  description text,
  base_type text CHECK (base_type = ANY (ARRAY['bisque'::text, 'glaze'::text, 'raku'::text, 'pit'::text, 'saggar'::text, 'crystalline'::text, 'other'::text])),
  atmosphere text CHECK (atmosphere = ANY (ARRAY['oxidation'::text, 'reduction'::text, 'neutral'::text])),
  temperature_curve jsonb NOT NULL,
  estimated_duration integer,
  clay_compatibility ARRAY,
  glaze_compatibility ARRAY,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  safety_notes text,
  kiln_specific_instructions text,
  shelf_configuration jsonb,
  last_used timestamp with time zone,
  usage_count integer DEFAULT 0,
  average_success_rate numeric,
  is_shared boolean DEFAULT false,
  parent_template_id uuid,
  version text DEFAULT '1.0'::text,
  change_notes text,
  performance_metrics jsonb,
  CONSTRAINT kiln_firing_templates_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_firing_templates_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT kiln_firing_templates_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_firing_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT kiln_firing_templates_parent_template_id_fkey FOREIGN KEY (parent_template_id) REFERENCES public.kiln_firing_templates(id)
);
CREATE TABLE public.kiln_firings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  kiln_id uuid NOT NULL,
  template_id uuid,
  name text,
  scheduled_start timestamp with time zone,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  atmosphere text,
  target_cone text,
  notes text,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'loading'::text, 'firing'::text, 'cooling'::text, 'completed'::text, 'cancelled'::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  operator_id uuid,
  target_temperature numeric,
  actual_temperature numeric,
  completion_notes text,
  firing_type text CHECK (firing_type = ANY (ARRAY['bisque'::text, 'glaze'::text, 'raku'::text, 'crystalline'::text])),
  booked_slots integer DEFAULT 0,
  CONSTRAINT kiln_firings_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_firings_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.profiles(id),
  CONSTRAINT kiln_firings_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT kiln_firings_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_firings_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.kiln_firing_templates(id),
  CONSTRAINT kiln_firings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_load_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kiln_shelf_id uuid NOT NULL,
  throw_id uuid,
  artist_id uuid NOT NULL,
  artist_name text NOT NULL,
  item_name text NOT NULL,
  clay_type text NOT NULL,
  glazes ARRAY,
  dimensions text,
  special_instructions text,
  shelf_position text,
  loaded_at timestamp with time zone DEFAULT now(),
  loaded_by uuid NOT NULL,
  status text DEFAULT 'loaded'::text CHECK (status = ANY (ARRAY['loaded'::text, 'firing'::text, 'cooling'::text, 'ready-for-pickup'::text, 'picked-up'::text])),
  pickup_notified timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_load_items_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_load_items_kiln_shelf_id_fkey FOREIGN KEY (kiln_shelf_id) REFERENCES public.kiln_shelves(id),
  CONSTRAINT kiln_load_items_artist_id_fkey FOREIGN KEY (artist_id) REFERENCES public.profiles(id),
  CONSTRAINT kiln_load_items_loaded_by_fkey FOREIGN KEY (loaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_loads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kiln_id uuid NOT NULL,
  firing_id uuid NOT NULL,
  total_items integer DEFAULT 0,
  load_started timestamp with time zone DEFAULT now(),
  load_completed timestamp with time zone,
  loaded_by uuid NOT NULL,
  assigned_employee_id uuid,
  notes text,
  photos ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_loads_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_loads_assigned_employee_id_fkey FOREIGN KEY (assigned_employee_id) REFERENCES public.profiles(id),
  CONSTRAINT kiln_loads_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_loads_firing_id_fkey FOREIGN KEY (firing_id) REFERENCES public.kiln_firings(id),
  CONSTRAINT kiln_loads_loaded_by_fkey FOREIGN KEY (loaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_performance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kiln_id uuid NOT NULL,
  firing_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  temperature numeric NOT NULL,
  target_temperature numeric,
  phase text CHECK (phase = ANY (ARRAY['heating'::text, 'holding'::text, 'cooling'::text])),
  gas_usage numeric,
  electric_usage numeric,
  notes text,
  recorded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_performance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_performance_logs_kiln_id_fkey FOREIGN KEY (kiln_id) REFERENCES public.kilns(id),
  CONSTRAINT kiln_performance_logs_firing_id_fkey FOREIGN KEY (firing_id) REFERENCES public.kiln_firings(id),
  CONSTRAINT kiln_performance_logs_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.kiln_shelves (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kiln_load_id uuid NOT NULL,
  level integer NOT NULL,
  capacity integer NOT NULL,
  used_capacity integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT kiln_shelves_pkey PRIMARY KEY (id),
  CONSTRAINT kiln_shelves_kiln_load_id_fkey FOREIGN KEY (kiln_load_id) REFERENCES public.kiln_loads(id)
);
CREATE TABLE public.kilns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  location_id uuid,
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['electric'::text, 'gas'::text, 'wood'::text, 'raku'::text])),
  manufacturer text,
  model text,
  serial_number text,
  capacity numeric,
  max_temp numeric,
  shelf_count integer,
  specs jsonb,
  status text DEFAULT 'available'::text CHECK (status = ANY (ARRAY['available'::text, 'loading'::text, 'firing'::text, 'cooling'::text, 'maintenance'::text, 'out-of-service'::text])),
  install_date date,
  warranty_expiry date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  shelf_configuration jsonb,
  last_fired timestamp with time zone,
  total_firings integer DEFAULT 0,
  maintenance_schedule jsonb,
  is_active boolean DEFAULT true,
  CONSTRAINT kilns_pkey PRIMARY KEY (id),
  CONSTRAINT kilns_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT kilns_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text,
  handle text UNIQUE,
  email text UNIQUE,
  type text DEFAULT 'artist'::text CHECK (type = ANY (ARRAY['artist'::text, 'studio'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  last_login timestamp with time zone,
  phone text,
  artist_plan USER-DEFINED NOT NULL DEFAULT 'artist-free'::artist_plan,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.ring_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL UNIQUE,
  is_enabled boolean DEFAULT false,
  api_key text,
  refresh_token text,
  connected_devices jsonb DEFAULT '[]'::jsonb,
  settings jsonb DEFAULT '{}'::jsonb,
  webhook_url text,
  last_sync timestamp with time zone,
  sync_status text DEFAULT 'pending'::text CHECK (sync_status = ANY (ARRAY['success'::text, 'error'::text, 'pending'::text])),
  error_log jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ring_integrations_pkey PRIMARY KEY (id),
  CONSTRAINT ring_integrations_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id)
);
CREATE TABLE public.studio_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['owner'::text, 'admin'::text, 'manager'::text, 'instructor'::text, 'member'::text, 'employee'::text])),
  token text NOT NULL UNIQUE,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'revoked'::text, 'expired'::text])),
  invited_by uuid NOT NULL,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_by uuid,
  accepted_at timestamp with time zone,
  location_id uuid,
  membership_type text CHECK (membership_type::studio_membership_plan IS NOT NULL),
  name text,
  CONSTRAINT studio_invites_pkey PRIMARY KEY (id),
  CONSTRAINT studio_invites_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT studio_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id),
  CONSTRAINT studio_invites_accepted_by_fkey FOREIGN KEY (accepted_by) REFERENCES public.profiles(id),
  CONSTRAINT studio_invites_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id)
);
CREATE TABLE public.studio_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  city text,
  state text,
  zip_code text,
  phone text,
  email text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT studio_locations_pkey PRIMARY KEY (id),
  CONSTRAINT studio_locations_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id)
);
CREATE TABLE public.studio_membership_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::studio_membership_application_status,
  location_id uuid,
  requested_membership_type text,
  experience text,
  interests ARRAY,
  goals text,
  referral_source text,
  emergency_contact jsonb,
  custom_fields jsonb,
  submitted_at timestamp with time zone DEFAULT now(),
  decided_at timestamp with time zone,
  decided_by uuid,
  decision_reason text,
  CONSTRAINT studio_membership_applications_pkey PRIMARY KEY (id),
  CONSTRAINT studio_membership_applications_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT studio_membership_applications_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT studio_membership_applications_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id),
  CONSTRAINT studio_membership_applications_requested_membership_type_fkey FOREIGN KEY (requested_membership_type) REFERENCES public.studio_membership_plans(plan_code),
  CONSTRAINT studio_membership_applications_decided_by_fkey FOREIGN KEY (decided_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.studio_membership_plans (
  plan_code text NOT NULL CHECK (plan_code::studio_membership_plan IS NOT NULL),
  name text NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  price_cents real CHECK (price_cents > 0.0::double precision),
  billing_interval text,
  CONSTRAINT studio_membership_plans_pkey PRIMARY KEY (plan_code)
);
CREATE TABLE public.studio_memberships (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  studio_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'member'::studio_role,
  created_at timestamp with time zone DEFAULT now(),
  status USER-DEFINED NOT NULL DEFAULT 'active'::studio_membership_status,
  location_id uuid NOT NULL,
  membership_type text CHECK (membership_type::studio_membership_plan IS NOT NULL),
  CONSTRAINT studio_memberships_pkey PRIMARY KEY (id),
  CONSTRAINT studio_memberships_studio_id_fkey FOREIGN KEY (studio_id) REFERENCES public.studios(id),
  CONSTRAINT studio_memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT studio_memberships_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.studio_locations(id)
);
CREATE TABLE public.studios (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  handle text NOT NULL UNIQUE,
  email text NOT NULL,
  description text,
  plan text DEFAULT 'studio-solo'::text CHECK (plan = ANY (ARRAY['studio-solo'::text, 'studio-duo'::text, 'studio-pro'::text, 'studio-unlimited'::text])),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  max_members integer,
  max_locations integer,
  website text,
  CONSTRAINT studios_pkey PRIMARY KEY (id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_type text NOT NULL CHECK (owner_type = ANY (ARRAY['profile'::text, 'studio'::text])),
  owner_id uuid NOT NULL,
  plan_code text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['active'::text, 'past_due'::text, 'canceled'::text, 'trialing'::text])),
  external_customer_id text,
  external_subscription_id text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id)
);